const PDFDocument = require('pdfkit');

const CURRENCIES = { USD: '$', EUR: '€', CAD: 'CA$', GBP: '£' };

function generateInvoicePDF(data) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const currency = CURRENCIES[data.currency || 'USD'] || '$';

  // Header
  doc.fontSize(28).fillColor('#1e40af').text('INVOICE', 50, 50);
  doc.fontSize(10).fillColor('#64748b')
    .text(`Invoice #: ${data.invoiceNumber || 'INV-' + Date.now().toString(36).toUpperCase()}`, 50, 85)
    .text(`Date: ${data.date || new Date().toLocaleDateString('en-US')}`, 50, 100)
    .text(`Due: ${data.dueDate || 'Upon Receipt'}`, 50, 115);

  // From
  doc.fontSize(12).fillColor('#1e293b').text(data.company || 'Your Company', 50, 150);
  if (data.companyAddress) doc.fontSize(9).fillColor('#64748b').text(data.companyAddress, 50, 168);

  // To
  doc.fontSize(10).fillColor('#94a3b8').text('BILL TO', 350, 150);
  doc.fontSize(12).fillColor('#1e293b').text(data.client || 'Client Name', 350, 168);
  if (data.clientAddress) doc.fontSize(9).fillColor('#64748b').text(data.clientAddress, 350, 186);

  // Table header
  const tableTop = 230;
  doc.fillColor('#f1f5f9').rect(50, tableTop, 500, 25).fill();
  doc.fillColor('#475569').fontSize(9);
  doc.text('DESCRIPTION', 60, tableTop + 8);
  doc.text('QTY', 340, tableTop + 8);
  doc.text('RATE', 400, tableTop + 8);
  doc.text('AMOUNT', 470, tableTop + 8);

  // Items
  let y = tableTop + 35;
  let subtotal = 0;
  (data.items || []).forEach(item => {
    const amount = (item.qty || 1) * (item.rate || 0);
    subtotal += amount;
    doc.fillColor('#1e293b').fontSize(10);
    doc.text(item.desc || item.description || 'Item', 60, y);
    doc.text(String(item.qty || 1), 340, y);
    doc.text(`${currency}${(item.rate || 0).toFixed(2)}`, 400, y);
    doc.text(`${currency}${amount.toFixed(2)}`, 470, y);
    y += 25;
  });

  // Totals
  y += 15;
  doc.moveTo(350, y).lineTo(550, y).strokeColor('#e2e8f0').stroke();
  y += 10;
  doc.fontSize(10).fillColor('#64748b').text('Subtotal:', 380, y);
  doc.fillColor('#1e293b').text(`${currency}${subtotal.toFixed(2)}`, 470, y);

  const taxRate = data.tax || 0;
  const taxAmount = subtotal * taxRate / 100;
  if (taxRate) {
    y += 20;
    doc.fillColor('#64748b').text(`Tax (${taxRate}%):`, 380, y);
    doc.fillColor('#1e293b').text(`${currency}${taxAmount.toFixed(2)}`, 470, y);
  }

  y += 25;
  const total = subtotal + taxAmount - (data.discount || 0);
  doc.fontSize(14).fillColor('#1e40af').text('Total:', 380, y);
  doc.text(`${currency}${total.toFixed(2)}`, 470, y);

  // Footer
  doc.fontSize(8).fillColor('#94a3b8').text('Generated by AIyamaya Dev Invoice Generator', 50, 750, { align: 'center' });

  return doc;
}

module.exports = { generateInvoicePDF };
